### ISSUE TITLE
Add function to copy vignette assets

### ISSUE THREAD

**Issue by cynthiahqy** [jacobbien/litr-project#46]
`litr::add_vignettes()` only copies across the `.Rmd` file, but sometimes extra files are needed render the vignette -- e.g. `.bib` files (see [units package](https://github.com/r-quantities/units/tree/e51bf61eb4a115ad1e4f066a6e91b83914eae751/vignettes)), or image files. It would be great to have a utility function to copy these assets over.

For example something like:

```r
add_vignette_assets <- function(files){
  fs::dir_create("vignettes")
  mapply(fs::file_copy, files, "vignettes")
}
```
That could be used as:
```
add_vignette_assets("../xmap-source-files/using-xmaps.bib", "vignettes")
```

**Comment by jacobbien** [comment]
Hi @cynthiahqy Thanks for this suggestion.  Good point.  It turns out I believe it would actually work for you to simply pass these additional files to `litr::add_vignettes()` like so:

```
add_vignettes(c("source-files/my_vignette.Rmd", "../xmap-source-files/using-xmaps.bib"))
```

Of course there would be no way for you to know that, so I'll update the name of the argument from `rmd_files` to `vignette_files` and update the documentation.  But before I do so, would you mind confirming that this works for you? Thanks!

**Comment by cynthiahqy** [comment]
Hi @jacobbien, your suggestion works for me. I was just adding my own function into my litr doc and calling that, but reusing the existing one is even better. Cheers!

**Comment by jacobbien** [comment]
[4518687](https://github.com/jacobbien/litr-project/commit/4518687402eaef9c0e77c0613def16d3f7329903) closes this issue.  I decided to leave `rmd_files` as an argument for backward compatibility; however, I added a second argument for other files.  Thanks @cynthiahqy !
